apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jhipster-gradle-postgresql-pvc
  namespace: opt-nc-ci-poc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jhipster-gradle-postgresql
  namespace: opt-nc-ci-poc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jhipster-gradle-postgresql
  template:
    metadata:
      labels:
        app: jhipster-gradle-postgresql
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: jhipster-gradle-postgresql-pvc
      containers:
        - name: postgres
          image: postgres:14.5
          env:
            - name: POSTGRES_USER
              value: jhipster-gradle
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: jhipster-gradle-postgresql
                  key: postgresql-password
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
              subPath: postgres
          resources:
            requests:
              memory: '512Mi'
              cpu: '500m'
            limits:
              memory: '1Gi'
              cpu: '1'
---
apiVersion: v1
kind: Service
metadata:
  name: jhipster-gradle-postgresql
  namespace: opt-nc-ci-poc
spec:
  selector:
    app: jhipster-gradle-postgresql
  ports:
    - port: 5432
